version: "3"

services:

  test_db:
    container_name: restaurant_test_db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    networks:
      - test_network

  test_runner:
    container_name: restaurant_api_tests
    image: restaurant_tests
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - test_network
    depends_on:
      - test_db

networks:
  test_network:
